### ISSUE TITLE
tableview editing is not working on swipe

### ISSUE THREAD

**Issue by pradeepispv** [DhruvinThumar/SDragView#2]
HI i added a table view in the dragview and editing style true for the table to swipe for edit,delete,etc.

But those swipes are not working when i use draview

**Comment by KMamedoff** [comment]
Did you manage to fix that issue?

**Comment by DhruvinThumar** [comment]
* **Replace Line No 34** with below code in SDragView file. 

super.init(frame: CGRect(x: 10, y:dragViewDefaultTopMargin , width: screenSize.width - 20, height: screenSize.height - dragViewAnimatedTopMargin))

* In main view controller, for tableview
   add UITableViewDelegate, UITableViewDataSource

private var myTableView: UITableView!
override func viewDidAppear(_ animated: Bool) {
        
        super.viewDidAppear(true)
        
        let dragView = SDragView(dragViewAnimatedTopSpace:25, viewDefaultHeightConstant:40)
        self.view.addSubview(dragView)
        
       // Simply add below code to add tableview in SDragView

        myTableView = UITableView(frame: CGRect(x: 20, y: 50, width: dragView.frame.size.width - 40, height: dragView.frame.size.height - 50))
        myTableView.register(UITableViewCell.self, forCellReuseIdentifier: "MyCell")
        myTableView.dataSource = self
        myTableView.delegate = self
        myTableView.autoresizingMask = [.flexibleWidth,.flexibleHeight]
        myTableView.tableFooterView = UIView()
        dragView.addSubview(myTableView)
 }


func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 20
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MyCell", for: indexPath as IndexPath)
        cell.textLabel!.text = "Test"
        return cell
    }

**For swipe for delete add below delegate methods**
func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if (editingStyle == .delete) {
           // toDoList.remove(at: indexPath.row)
            
            //UserDefaults.standard.set(toDoList, forKey: "toDoList")
            tableView.reloadData()
        }
    }
    
    func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCellEditingStyle {
        return .delete
    }
